apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-internal-service
spec:
  selector:
    app: node-testing
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP